### ISSUE TITLE
question: VST for osx ?

### ISSUE THREAD

**Issue by gorhgorh** [sophiapoirier/destroyfx#66] opened 2024-10-12 13:53 UTC
I just wanted to make sure that the installers for osx only installs AU plugins ?

I could not find vst version on my machine and the audio unit install times matched my install.

some (bitwig for example) DAWS does not support AU plugins. so I'm out of DFX as of now :)

best and thanks for the really cool things you released

**Comment by sophiapoirier** [comment] 2024-10-12 17:12
Yes no VST for Mac, [see first FAQ item](http://destroyfx.org/faq.html#incompatibility) for some workarounds.
I also suggest lobbying Bitwig for AU support, they certainly have vastly more development resources than us.
Glad though that you are enjoying our effects!

duplicate of #59

**Comment by sophiapoirier** [comment] 2024-10-12 17:13
duplicate of #59

**Comment by sophiapoirier** [comment] 2024-10-12 17:13
duplicate of #59

**Closed by sophiapoirier** 2024-10-12 17:13 UTC
